[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = 'forge-cache'

auto_detect_solc = true
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
